#!/usr/bin/bash


source Parameters

all_files=`ls`

for file_name in $all_files
do
    exclude_file=`echo "$exc_files" | grep "$file_name" -o`
    if [ -d "$file_name" ] && [ "$exclude_file" = ""  ]
    then
        cd $file_name
        ../ProblemClean
        cd ../
    fi
done

#
#END-OF-FILE
#

