#!/usr/bin/bash

export exc_files="scripts reports common reference 0 constant system 0.orig chemkin"
if [ -v studied_solvers ]
then
    echo "Studying solvers: $studied_solvers"
else
    studied_solvers=
fi


#
#
#

