#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch chtMultiRegionCentralFoam-200CPL.foam
runApplication blockMesh -region fluid
cp -rf 0.orig 0
runApplication setFields -region fluid
runApplication `getApplication`
runApplication postProcess -func sampleDict -region fluid
python ../../../scripts/one_d_perf_gas_calc_errors.py postProcessing/sampleDict/fluid/0.25/line_T_p_rho_U.csv  ../../reference/exact.out > solution_errors

#------------------------------------------------------------------------------
