#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch vofTwoPhaseCentralFoam-500CPL.foam
runApplication blockMesh
cp -rf 0.orig 0
runApplication setFields
runApplication `getApplication`
runApplication postProcess -func sampleDict


#------------------------------------------------------------------------------
