name: CI/CD Pipeline with Border0 GitHub Action
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Manual trigger
        required: false
        default: false

jobs:
  gh-action-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: 2406
      - run: git clone -b digitef-v2312 https://github.com/mkraposhin/QGDsolver.git
      - run: |
          . /usr/lib/openfoam/openfoam2406/etc/bashrc
          cd  /home/runner/work/VnV/VnV/QGDsolver
          ./SwitchDest
          ./SwitchDest USER
          mkdir -p $FOAM_USER_APPBIN
          mkdir -p $FOAM_USER_LIBBIN
          export > cenv
          ./Allwmake
          cd ../
      - name: A step that will always fail
        run: |
            echo "this step will wait 10 seconds and always fails"
            sleep 10
            exit 1
      - name: Start Border0 in case of failure.
        if: failure()
        uses: borderzero/gh-action@v2
        with:
          token: ${{ secrets.BORDER0_GHA_LOGIN }}
          wait-for: 20
